version: '3.8'
services:
  backend:
    container_name: events
    build: ./
    ports:
      - "5001:5001"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/onboarding
      RABBITMQ_URL: amqp://rabbit:rabbit@rabbitmq:5672
    networks:
      - onboarding-network
networks:
  onboarding-network:
    external: true
    name: onboarding-network