spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/onboarding
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  liquibase:
    enabled: 'true'

rabbitmq:
  talkdesk:
    consumer:
      connection:
        host: localhost
        username: rabbit
        password: rabbit
        vhost:
        protocol: amqp
        port: 5672